version: '3.7'

services:
  web:
    container_name: web-app-calculator-03
    hostname: app
    build: ./
    ports:
      - "5003:5003"
    depends_on:
      - mariadb

  mariadb:
    container_name: web-mariadb-03
    hostname: mariadb
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 3_WebCalculatorDB
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "5023:3306"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - "5043:5043"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:5043
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    ports:
      - "2181:2181"
