version: '3.7'

services:
  web:
    container_name: web-app-calculator-03
    hostname: app
    build: ./
    ports:
      - "5003:5003"
    depends_on:
      - mariadb

  mariadb:
    container_name: web-mariadb-03
    hostname: mariadb
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 3_WebCalculatorDB
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "5023:3306"
