version: '3.7'

services:
  web:
    container_name: web-app-calculator
    hostname: app
    build: ./
    ports:
      - "0.0.0.0:5003:5003"
    depends_on:
      - mariadb

  mariadb:
    container_name: web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: calculator_3_db
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:3306:3306"

networks:
  calculator-network:
    driver: bridge
